import { stats } from "./enemies";

const HEROES = {
  HAWTHORN: {
    name: "Hawthorn, the Green Knight",
    image: null,
    sounds: {},
    level: 1,
    health: stats.ranks.AVERAGE,
    defense: stats.ranks.AVERAGE,
    damage: stats.ranks.AVERAGE,
    hitChance: stats.ranks.AVERAGE,
    critChance: stats.ranks.LOW,
    speed: stats.ranks.AVERAGE,
    armorType: stats.types.PHYSICAL,
    damageType: stats.types.PHYSICAL,
    weaknesses: [stats.types.FIRE],
    resistances: [stats.types.WATER],
    behavior: stats.behaviors.SUPPORTIVE,
    passive: () => {},
    active1: () => {},
    active2: () => {},
  },
}

// HERO_NAME: {
//   name: "",
//   image: null,
//   sounds: {},
//   level: 1,
//   health: stats.ranks.,
//   defense: stats.ranks.,
//   damage: stats.ranks.,
//   hitChance: stats.ranks.,
//   critChance: stats.ranks.,
//   speed: stats.ranks.,
//   armorType: stats.types.,
//   damageType: stats.types.,
//   weaknesses: [],
//   resistances: [],
//   behavior: stats.behaviors.,
//   passive: () => {},
//   active1: () => {},
//   active2: () => {},
// },